[versions]

android = "8.9.1"
kotlin = "2.1.20"

sdk-min = "26"
sdk-compile = "35"
sdk-target = "35"
jvm-target = "17"

[libraries]

[plugins]

library = { id = "com.android.library", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }